import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import YAML from "yaml";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const sdkDir = path.resolve(scriptDir, "..");
const specPath = path.resolve(sdkDir, "openapi/openapi.yaml");
const outputPath = path.resolve(sdkDir, "generated/operation-scopes.ts");

const source = await readFile(specPath, "utf8");
const document = YAML.parse(source);

const entries = [];

for (const [pathname, pathItem] of Object.entries(document.paths ?? {})) {
  if (!pathItem || typeof pathItem !== "object") {
    continue;
  }

  for (const [method, operation] of Object.entries(pathItem)) {
    if (!operation || typeof operation !== "object") {
      continue;
    }

    const operationId = operation.operationId;
    const requiredScopes = operation["x-required-scopes"];

    if (!operationId || !Array.isArray(requiredScopes)) {
      continue;
    }

    entries.push({
      operationId,
      method: method.toUpperCase(),
      path: pathname,
      scopes: [...requiredScopes].sort()
    });
  }
}

entries.sort((left, right) => left.operationId.localeCompare(right.operationId));

const mapBody = entries
  .map((entry) => {
    const scopeList = entry.scopes.map((scope) => `"${scope}"`).join(", ");

    return [
      `  ${JSON.stringify(entry.operationId)}: {`,
      `    method: ${JSON.stringify(entry.method)},`,
      `    path: ${JSON.stringify(entry.path)},`,
      `    scopes: [${scopeList}] as const`,
      "  }"
    ].join("\n");
  })
  .join(",\n");

const fileContents = `// Generated by scripts/generate-scopes.mjs. Do not edit manually.

export const operationScopes = {
${mapBody}
} as const;

export type ManagementOperationId = keyof typeof operationScopes;
export type ManagementScope =
  (typeof operationScopes)[ManagementOperationId]["scopes"][number];
`;

await writeFile(outputPath, fileContents);
